### ISSUE TITLE
Should the demo set exception message as span's status description

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-demo#1412] opened 2024-02-26 16:04 UTC
# Bug Report

Which version of the demo you are using? : main branch

## Symptom

https://github.com/open-telemetry/opentelemetry-demo/blob/main/src/cartservice/src/services/CartService.cs#L75 Is storing Exception message into status description. As per the [SetStatus spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#set-status), the description should be documented and predictable. I am wondering if this is an intentional thing or a leftover from some previous state?

https://github.com/open-telemetry/opentelemetry-dotnet/pull/5025 OTel .NET's instrumentation library removed setting exception message to status.description before its 1st stable release....

**What is the expected behavior?**

Not sure. This is more like a question - should we set exception message into status description.

**Comment by puckpuck** [comment] 2024-03-01 02:39
I believe we are doing this properly. The specification says that Instrumentation Libraries should set this to be documented and predictable. Since this is not an instrumentation library, what we are doing would be the expected behavior to see the error message as returned to our code if an error occurs.

> When the status is set to Error by Instrumentation Libraries, the Description SHOULD be documented and predictable.

**Comment by puckpuck** [comment] 2024-03-21 19:40
Closing this issue since we are setting this in the application code and not as part of an instrumentation library. Feel free to re-open if you feel otherwise and we can further discuss.

**Closed by puckpuck** 2024-03-21 19:40 UTC
Labels: bug
