### ISSUE TITLE
Renovate is opening PRs with no files changed

### ISSUE THREAD

**Issue by julianocosta89** [open-telemetry/opentelemetry-demo#1095] opened 2023-09-04 05:31 UTC
# Bug Report

Renovate is opening weekly PRs with 0 files changed:

- https://github.com/open-telemetry/opentelemetry-demo/pull/1094
- https://github.com/open-telemetry/opentelemetry-demo/pull/1093
- https://github.com/open-telemetry/opentelemetry-demo/pull/1092
- https://github.com/open-telemetry/opentelemetry-demo/pull/1071
- https://github.com/open-telemetry/opentelemetry-demo/pull/1070
- https://github.com/open-telemetry/opentelemetry-demo/pull/1069
- https://github.com/open-telemetry/opentelemetry-demo/pull/1068
- https://github.com/open-telemetry/opentelemetry-demo/pull/1067
- https://github.com/open-telemetry/opentelemetry-demo/pull/1066

**Comment by secustor** [comment] 2023-10-28 20:11
Some recommendations here:
- instead of merging from main/master use the rebase check box on the PR or the dashboard. That way Renovate will keep managing the PR. 
- This is the case to allow devs to fix regressions.
- If Renovate still manages the PR it will close it if the PR is not necessary anymore.

**Comment by mviitane** [comment] 2023-12-08 12:06
This problem seems to be fixed, a few weeks without duplicates.

**Closed by mviitane** 2023-12-08 12:06 UTC
Labels: bug
