### ISSUE TITLE
Issue starting demo with Podman

### ISSUE THREAD

**Issue by dd4gg** [open-telemetry/opentelemetry-demo#993] opened 2023-07-20 22:59 UTC
When I execute podman-compose, I hit the same issue:

$ podman pull ghcr.io/open-telemetry/demo:1.4.0-traceBasedTests
Trying to pull ghcr.io/open-telemetry/demo:1.4.0-traceBasedTests...
Error: initializing source docker://ghcr.io/open-telemetry/demo:1.4.0-traceBasedTests: reading manifest 1.4.0-traceBasedTests in ghcr.io/open-telemetry/demo: manifest unknown

Is this a valid container that is supposed to be in the ghcr.io ?

**Comment by austinlparker** [comment] 2023-07-21 14:05
Hi, I've transferred this issue to the demo repository.

**Comment by styblope** [comment] 2023-11-19 22:32
I could replicate the issue and found the cause with multiple things playing out:

1. The image `ghcr.io/open-telemetry/demo:1.4.0-traceBasedTests` isn't indeed present in the repository because it isn't included in [the GHA image build workflow](https://github.com/open-telemetry/opentelemetry-demo/blob/main/.github/workflows/build-images.yml#L97).
2. The traceBasedTests service is associated with a [profile](https://github.com/open-telemetry/opentelemetry-demo/blob/main/docker-compose.yml#L782) in `docker-compose.yml`. [Docker-compose services with assigned profiles](https://docs.docker.com/compose/profiles/) aren't started unless one explicitly enables them using ``--profile` option. Therefore, the service should not be started using the normal demo startup command.
3. The reason podman-compose wants to pull the (nonexistent) image is because it doesn't yet implement profiles in the current v1.0.6 release; it will effectively start all containers declared in the compose file regardless the profile settings. The option is already [merged in podman-compose upstream](https://github.com/containers/podman-compose/pull/592) so hopefully due out soon.

If the various podman quirks get resolved, I think it would be worth opening up a discussion for qualifying podman as an inclusive build/run option next to docker.

**Comment by austinlparker** [comment] 2024-02-19 16:34
Is this still an issue in 1.8?

**Comment by puckpuck** [comment] 2024-03-21 19:58
It's been 11+ months since the PR to fix this in podman compose was merged, and still no release from their platform. Do we have any insight on if/when they will do a release?

The other way is to workaround the issue in podman compose and publish a `traceBasedTests` image as well as everything else we do. We already publish a `frontendTests` one, so I don't see why we can't add this one too.

**Closed** 2024-04-08 14:39 UTC
Labels: bug
