### ISSUE TITLE
Frontend pages should have title rather than URL.

### ISSUE THREAD

**Issue by austinlparker** [open-telemetry/opentelemetry-demo#526] opened 2022-10-23 20:38 UTC
Currently the page title on the frontend is just the URL route; We should display proper ones instead.

**Comment by cartersocha** [comment] 2022-11-27 18:51
Duplicate of info in #327. Closing in favor of that issue. There is a lot of debt / enhancements building up on the front end. A good sig topic

**Closed by cartersocha** 2022-11-27 18:51 UTC
Labels: enhancement
