### ISSUE TITLE
docker build failed due to wget Unable to establish SSL connection

### ISSUE THREAD

**Issue by yongpro** [open-telemetry/opentelemetry-demo#1017] opened 2023-07-25 08:39 UTC
# Question
My laptop is MBP M1 Pro, and installed vmware arm64 version.
Then install ubuntu 22.04.2 TLS arm version in vmware.
Then I git clone the demo and docker-compose up build in ubuntu vm, have follow alarm, need your kindly help...

```
root@rdma1:~/opentelemetry-demo# docker system prune -a
root@rdma1:~/opentelemetry-demo# docker-compose up --build
Creating network "opentelemetry-demo" with driver "bridge"
Pulling ffs_postgres (postgres:14)...
14: Pulling from library/postgres
3ae0c06b4d3a: Pull complete
4a34531fd37c: Pull complete
529fb828a0d2: Pull complete
......
Removing intermediate container 6cb272d9aa21
 ---> 37a374cf154e
Step 8/44 : WORKDIR /app
 ---> Running in d9f47e0e233b
Removing intermediate container d9f47e0e233b
 ---> 70989d7b0b97
Step 9/44 : RUN mix local.hex --force --verbose
 ---> Running in 964a36fdbe15
* creating /root/.mix/archives/hex-2.0.6
Removing intermediate container 964a36fdbe15
 ---> 7eff9382d508
Step 10/44 : RUN mix local.rebar --force --verbose
 ---> Running in 6a9906c5e511
* creating /root/.mix/elixir/1-15/rebar3
Removing intermediate container 6a9906c5e511
 ---> f73c30eeaebd
Step 11/44 : RUN wget https://s3.amazonaws.com/rebar3/rebar3 && chmod +x rebar3 && mv rebar3 ~/.mix
 ---> Running in 389585931d76
--2023-07-25 08:13:07--  https://s3.amazonaws.com/rebar3/rebar3
Resolving s3.amazonaws.com (s3.amazonaws.com)... 52.217.169.104, 54.231.203.184, 52.217.115.216, ...
Connecting to s3.amazonaws.com (s3.amazonaws.com)|52.217.169.104|:443... connected.
GnuTLS: Error in the pull function.
Unable to establish SSL connection.
The command '/bin/sh -c wget https://s3.amazonaws.com/rebar3/rebar3 && chmod +x rebar3 && mv rebar3 ~/.mix' returned a non-zero code: 4
ERROR: Service 'featureflagservice' failed to build : Build failed
```

Thanks
Frank

**Comment by julianocosta89** [comment] 2023-07-25 08:46
Could you try the newer version of docker compose?
Without the `-`.

Try to build the services first:

```shell
docker compose build
```

Then run it:
```shell
docker compose up
```

**Comment by yongpro** [comment] 2023-07-25 09:47
after use new command, have similar alarm...

```
root@rdma1:~/opentelemetry-demo# docker compose build
[+] Building 12.4s (40/65)                                                                                                                        
 => [kafka internal] load build definition from Dockerfile                                                                                   0.0s
 => => transferring dockerfile: 1.19kB                                                                                                       0.0s
 => [kafka internal] load .dockerignore                                                                                                      0.0s
 => => transferring context: 1.18kB                                                                                                          0.0s
 => [kafka internal] load metadata for docker.io/confluentinc/cp-kafka:latest-ubi8                                                           0.9s
 => [featureflagservice internal] load build definition from Dockerfile                                                                      0.0s
 => => transferring dockerfile: 3.36kB                                                                                                       0.0s
 => [featureflagservice internal] load .dockerignore                                                                                         0.0s
 => => transferring context: 1.18kB                                                                                                          0.0s
 => [featureflagservice internal] load metadata for docker.io/library/debian:buster-20230612-slim                                            0.9s
 => [featureflagservice internal] load metadata for docker.io/hexpm/elixir:1.15.4-erlang-26.0.2-debian-buster-20230612-slim                  0.9s
 => [otelcol internal] load build definition from Dockerfile                                                                                 0.0s
 => => transferring dockerfile: 997B                                                                                                         0.0s
 => [otelcol internal] load .dockerignore                                                                                                    0.0s
 => => transferring context: 1.18kB                                                                                                          0.0s
 => [otelcol internal] load metadata for docker.io/library/alpine:latest                                                                     0.9s
 => [otelcol internal] load metadata for docker.io/library/golang:latest                                                                     1.0s
 => [otelcol internal] load metadata for docker.io/library/alpine:3.16                                                                       0.9s
 => [kafka] importing cache manifest from ghcr.io/open-telemetry/demo:1.4.0-kafka                                                            0.0s
 => CANCELED [kafka] https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/download/v1.23.0/opentelemetry-javaagen  11.5s
 => [kafka 1/3] FROM docker.io/confluentinc/cp-kafka:latest-ubi8@sha256:d3acff0466ec26c8048b75c7185dbc9c9d718cb1111f0cc00d535df073d71103     0.0s
 => [featureflagservice] importing cache manifest from ghcr.io/open-telemetry/demo:1.4.0-featureflagservice                                  3.7s
 => [featureflagservice builder  1/25] FROM docker.io/hexpm/elixir:1.15.4-erlang-26.0.2-debian-buster-20230612-slim@sha256:4869c1e8df9cb2f5  0.0s
 => [featureflagservice internal] load build context                                                                                         0.0s
 => => transferring context: 5.83kB                                                                                                          0.0s
 => [featureflagservice stage-1 1/6] FROM docker.io/library/debian:buster-20230612-slim@sha256:738002a6e94e8629a0f869be8ea56519887979d5ed41  0.0s
 => ERROR [otelcol] importing cache manifest from ghcr.io/open-telemetry/demo:1.4.0-otelcol                                                  1.0s
 => [otelcol build 1/7] FROM docker.io/library/golang:latest@sha256:cfc9d1b07b1ef4f7a4571f0b60a99646a92ef76adb7d9943f4cb7b606c6554e2         0.0s
 => [otelcol internal] load build context                                                                                                    0.0s
 => => transferring context: 294B                                                                                                            0.0s
 => [otelcol stage-2 1/4] FROM docker.io/library/alpine@sha256:82d1e9d7ed48a7523bdebc18cf6290bdb97b82302a8a9c27d4fe885949ea94d1              0.0s
 => [otelcol certs 1/2] FROM docker.io/library/alpine:3.16@sha256:cbe5d5973103a2d03408d1689a6efde4ea4920bde9f4b51fe7872e60ce2d8e56           0.0s
 => CACHED [featureflagservice stage-1 2/6] RUN apt-get update -y && apt-get install -y openssl libncurses5 locales curl   && apt-get clean  0.0s
 => CACHED [featureflagservice stage-1 3/6] RUN sed -i '/en_US.UTF-8/s/^# //g' /etc/locale.gen && locale-gen                                 0.0s
 => CACHED [featureflagservice stage-1 4/6] WORKDIR /app                                                                                     0.0s
 => CACHED [featureflagservice stage-1 5/6] RUN chown nobody /app                                                                            0.0s
 => CACHED [featureflagservice builder  2/25] RUN apt-get update -y && apt-get install -y build-essential git wget     && apt-get clean &&   0.0s
 => CACHED [featureflagservice builder  3/25] WORKDIR /app                                                                                   0.0s
 => [featureflagservice builder  4/25] RUN mix local.hex --force --verbose                                                                   3.2s
 => CACHED [otelcol certs 2/2] RUN apk --update add ca-certificates                                                                          0.0s
 => CACHED [otelcol stage-2 2/4] COPY --from=certs /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt                     0.0s
 => CACHED [otelcol build 2/7] RUN curl -L -o /builder https://github.com/open-telemetry/opentelemetry-collector/releases/download/cmd%2Fbu  0.0s
 => CACHED [otelcol build 3/7] RUN chmod +x /builder                                                                                         0.0s
 => CACHED [otelcol build 4/7] WORKDIR /build                                                                                                0.0s
 => CACHED [otelcol build 5/7] COPY ./src/otelcollector/manifest.yml ./                                                                      0.0s
 => CANCELED [otelcol build 6/7] RUN /builder --config ./manifest.yml --output-path /build/_build                                            7.7s
 => [featureflagservice builder  5/25] RUN mix local.rebar --force --verbose                                                                 3.8s
 => ERROR [featureflagservice builder  6/25] RUN wget https://s3.amazonaws.com/rebar3/rebar3 && chmod +x rebar3 && mv rebar3 ~/.mix          0.6s
------
 > [otelcol] importing cache manifest from ghcr.io/open-telemetry/demo:1.4.0-otelcol:
------
------
 > [featureflagservice builder  6/25] RUN wget https://s3.amazonaws.com/rebar3/rebar3 && chmod +x rebar3 && mv rebar3 ~/.mix:
0.262 --2023-07-25 09:47:06--  https://s3.amazonaws.com/rebar3/rebar3
0.262 Resolving s3.amazonaws.com (s3.amazonaws.com)... 52.216.214.128, 52.216.248.158, 52.216.62.232, ...
0.312 Connecting to s3.amazonaws.com (s3.amazonaws.com)|52.216.214.128|:443... connected.
0.550 GnuTLS: Error in the pull function.
0.551 Unable to establish SSL connection.
------
failed to solve: process "/bin/sh -c wget https://s3.amazonaws.com/rebar3/rebar3 && chmod +x rebar3 && mv rebar3 ~/.mix" did not complete successfully: exit code: 4
```

**Comment by julianocosta89** [comment] 2023-07-25 11:47
If you have docker in your mac, are you able to build the demo locally?
If yes, the issue is with this vmware and Ubuntu setup, not sure how to help there.

**Comment by yongpro** [comment] 2023-07-25 13:17
Due to poor docker performance in macos, so I am not install docker. 
I have a powerful server in lab, but that is offline... could we install demo by offline?

**Comment by julianocosta89** [comment] 2023-07-25 19:27
That would work, but you would need to pull or build all the images, tar them and import into docker in your offline host.
Looks like a lot of effort tbh.

We have users simply using Docker for Desktop in Mac, and that works for them.

**Comment by leonardo3791** [comment] 2023-08-01 09:43
Hello, have the same issue on a AWS EC2 instance where I've installed Docker and I have tried to start the demo with the following error
```
 Running 1/1
 ! otelcol Warning                                                                                                                               0.8s
 Building 1.4s (17/20)
 => [internal] load build definition from Dockerfile                                                                                             0.0s
 => => transferring dockerfile: 32B                                                                                                              0.0s
 => [internal] load .dockerignore                                                                                                                0.0s
 => => transferring context: 35B                                                                                                                 0.0s
 => [internal] load metadata for docker.io/library/alpine:latest                                                                                 0.5s
 => [internal] load metadata for docker.io/library/golang:latest                                                                                 0.5s
 => [internal] load metadata for docker.io/library/alpine:3.16                                                                                   0.5s
 => ERROR importing cache manifest from ghcr.io/open-telemetry/demo:1.4.0-otelcol                                                                0.2s
 => [stage-2 1/4] FROM docker.io/library/alpine@sha256:82d1e9d7ed48a7523bdebc18cf6290bdb97b82302a8a9c27d4fe885949ea94d1                          0.0s
 => [internal] load build context                                                                                                                0.0s
 => => transferring context: 294B                                                                                                                0.0s
 => [certs 1/2] FROM docker.io/library/alpine:3.16@sha256:cbe5d5973103a2d03408d1689a6efde4ea4920bde9f4b51fe7872e60ce2d8e56                       0.0s
 => [build 1/7] FROM docker.io/library/golang:latest@sha256:010a0ffe47398a3646993df44906c065c526eabf309d01fb0cbc9a5696024a60                     0.0s
 => CACHED [certs 2/2] RUN apk --update add ca-certificates                                                                                      0.0s
 => CACHED [stage-2 2/4] COPY --from=certs /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt                                 0.0s
 => CACHED [build 2/7] RUN curl -L -o /builder https://github.com/open-telemetry/opentelemetry-collector/releases/download/cmd%2Fbuilder%2Fv0.8  0.0s
 => CACHED [build 3/7] RUN chmod +x /builder                                                                                                     0.0s
 => CACHED [build 4/7] WORKDIR /build                                                                                                            0.0s
 => CACHED [build 5/7] COPY ./src/otelcollector/manifest.yml ./                                                                                  0.0s
 => ERROR [build 6/7] RUN /builder --config ./manifest.yml --output-path /build/_build                                                           0.6s
 importing cache manifest from ghcr.io/open-telemetry/demo:1.4.0-otelcol:
 [build 6/7] RUN /builder --config ./manifest.yml --output-path /build/_build:
0 0.448 /bin/sh: 1: /builder: Exec format error
failed to solve: executor failed running [/bin/sh -c /builder --config ./manifest.yml --output-path /build/_build]: exit code: 126
```

I also tried to pull the image:
`
docker pull ghcr.io/open-telemetry/demo:1.4.0-otelcol
`
`
Error response from daemon: manifest unknown
`
Have you found a solution?

Thanks,
Leonardo

**Comment by julianocosta89** [comment] 2023-08-05 12:15
@leonardo3791 could you try:

```
docker compose build otelcol --no-cache
```

**Comment by puckpuck** [comment] 2024-01-19 01:34
@leonardo3791 is this still an issue with the latest release?

**Comment by austinlparker** [comment] 2024-02-19 16:34
Closing this as part of issue cleanup. If there's anything that needs to be done, please create a new issue.

**Closed by austinlparker** 2024-02-19 16:34 UTC
Labels: question

**Comment by mu-arkhipov** [comment] 2024-02-20 21:03
Experience the same problem, `Docker version 24.0.6, build ed223bc`
