### ISSUE TITLE
FeatureFlagservice is broken 

### ISSUE THREAD

**Issue by munibshah** [open-telemetry/opentelemetry-demo#1050] opened 2023-08-11 03:44 UTC
# Bug Report

Which version of the demo you are using? 1.4-latest

## Symptom

When I try to edit featureflags, the POST request path goes to feature/featureflags/edit when it should go to /featureflags/edit

**What is the expected behavior?**

Editing the flag should POST to /featureflags/edit

**Comment by rossmcdonald** [comment] 2023-09-12 21:35
I ran into this issue as well, and it was caused by me accessing the featureflagservice directly. Apparently it should be accessed through the **frontendproxy** service, which is where the `feature/` prefix comes into play. For example, hitting:

```
POST http://otel-demo-frontendproxy:8080/feature/featureflags/1
```

(where `otel-demo-frontendproxy` is the service name in k8s, or the hostname of the frontendproxy)

I haven't been able to find this documented anywhere outside of Github issues, so maybe this issue should be repurposed for updating the docs on how to update FF's since [this doc](https://opentelemetry.io/docs/demo/feature-flags/) doesn't mention it at all.

**Comment by DerekZH** [comment] 2024-01-15 21:48
This line is adding /feature prefix to all urls:

https://github.com/open-telemetry/opentelemetry-demo/blob/main/src/featureflagservice/config/config.exs#L19

changing: 

```  
url: [host: "localhost", path: "/feature"]
```

to 

```
  url: [host: "localhost"],
```

frontend rendering works now. 

@austinlparker : is there a reason why this `/feature/` prefix to the urls is needed?

**Comment by puckpuck** [comment] 2024-01-16 22:25
The demo is meant to be accessed through the frontend-proxy service only on the `/feature/` route. This is so the demo only needs to expose a single port for all UIs/services that need to be exposed.

I will close this issue since it refers to an older demo version, and the feature flag service has received updates that specifically changed the edit page to introduce new functionality.

**Closed by puckpuck** 2024-01-16 22:25 UTC
Labels: bug
